%YAML 1.2
---
model: ./model/neureflect.yaml

dataloader:
    scene_path: ../data/neulight/Salon2
    num_workers: 4
    batch_size: 1
    num_rays_per_image: 10000
    visualize_image_shape: [240, 320]

trainer:
    accelerator: gpu
    devices: -1
    max_epochs: 200
    log_every_n_steps: 10
    num_sanity_val_steps: 1
    profiler: simple

wandb_logger:
    name: NeuReflect
    entity: tomnotch
    project: NeuLight
